version: '3.1'
services:
  Backend:
    image: 'app.jar:latest'
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./src/main/resources/
        target: /src/main/resources/
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - DB_URL=postgresql://PostgreSQL:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5